-- Project: Gate_Textures
-- Code: Kenuvis
-- Date: 28.07.2012

Gate.edgeFiles = {	"Interface/FriendsFrame/UI-Toast-Border", 				-- 1
				"Interface/FriendsFrame/PendingFriendGlow", 				-- 2
				"Interface/ACHIEVEMENTFRAME/UI-Achievement-WoodBorder",	-- 3
				"Interface/CHARACTERFRAME/UI-Party-Border",				-- 4
				"Interface/DialogFrame/UI-DialogBox-Border",				-- 5 
				"Interface/DialogFrame/UI-DialogBox-Gold-Border",			-- 6
				"Interface/LFGFRAME/LFGBorder",						-- 7
				"Interface/Tooltips/ChatBubble-Border",					-- 8
				"Interface/Tooltips/UI-Tooltip-Border"}
Gate.bgFiles = {		"Interface/DialogFrame/UI-DialogBox-Background-Dark",		-- 1
				"Interface/DialogFrame/UI-DialogBox-Background",			-- 2
				"Interface/DialogFrame/UI-DialogBox-Gold-Background",		-- 3
				"Interface/Tooltips/ChatBubble-Background",				-- 4
				"Interface/Tooltips/UI-Tooltip-Background",				-- 5
				"Interface/LFGFRAME/LFGFrame-SearchIcon-Background",		-- 6
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-DUNGEONWALL",	-- 7
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-HEROIC",			-- 8
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-QUESTPAPER",		-- 9
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-TROLLPOCALYPSE",	-- 10
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-RANDOMDUNGEON",	-- 11
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Ahnkalet",		-- 12
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-AQRuins",			-- 13
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-AQTemple",		-- 14
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-ArgentDungeon",	-- 15
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-ArgentRaid",		-- 16
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Auchindoun",		-- 17
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-AzjolNerub",		-- 18
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-BlackfathomDeeps",	-- 19
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-BlackrockDepths",	-- 20
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-BlackrockSpire",	-- 21
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-BlackTemple",		-- 22
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-BlackwingLair",		-- 23
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Brew",			-- 24
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-CavernsOfTime",	-- 25
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-ChamberOfAspects",	-- 26
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-CoilFang",		-- 27
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Deadmines",		-- 28
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-DireMaul",		-- 29
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-DrakTharon",		-- 30
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Gnomeregan",		-- 31
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-GruulsLair",		-- 32
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Gundrak",			-- 33
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Halloween",		-- 34
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-HallsofLightning",	-- 35
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-HallsofReflection",	-- 36
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-HallsofStone",		-- 37
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-HellfireCitadel",		-- 38
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-HellfireCitadelRaid",	-- 39
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-HyjalPast",		-- 40
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-IcecrownCitadel",	-- 41
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Karazhan",		-- 42
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Love",			-- 43
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-MagistersTerrace",	-- 44
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Malygos",			-- 45
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Maraudon",		-- 46
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-MoltenCore",		-- 47
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Naxxramas",		-- 48
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Outland",			-- 49
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-PitofSaron",		-- 50
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-RagefireChasm",	-- 51
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-RazorfenDowns",	-- 52
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-RazorfenKraul",		-- 53
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-ScarletMonastery",	-- 54
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Scholomance",		-- 55
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-ShadowFangKeep",	-- 56
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-StormwindStockades",-- 57
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Stratholme",		-- 58
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Summer",			-- 59
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-SunkenTemple",	-- 60
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Sunwell",			-- 61
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-TempestKeep",		-- 62
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-TheForgeofSouls",	-- 63
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-TheNexus",		-- 64
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-TheOculus",		-- 65
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-TheVioletHold",		-- 66
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Uldaman",		-- 67
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Ulduar",			-- 68
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-Utgarde",			-- 69
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-UtgardePinnacle",	-- 70
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-VaultOfArchavon",	-- 71
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-WailingCaverns",	-- 72
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-ZulAman",		-- 73
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-ZulFarak",		-- 74
				"Interface/LFGFRAME/UI-LFG-BACKGROUND-ZulGurub",		-- 75
				"Interface/LFGFRAME/UI-LFG-HOLIDAY-BACKGROUND-Brew",	-- 76
				"Interface/LFGFRAME/UI-LFG-HOLIDAY-BACKGROUND-Halloween",	-- 78
				"Interface/LFGFRAME/UI-LFG-HOLIDAY-BACKGROUND-Love",	-- 79
				"Interface/LFGFRAME/UI-LFG-HOLIDAY-BACKGROUND-Summer",	-- 80
				"Interface/ACHIEVEMENTFRAME/UI-Achievement-Parchment-Horizontal-Desaturated", -- 81
				"Interface/ACHIEVEMENTFRAME/UI-Achievement-Parchment-Horizontal", -- 82
				"Interface/ACHIEVEMENTFRAME/UI-Achievement-StatsBackground", -- 83
				"Interface/ACHIEVEMENTFRAME/UI-GuildAchievement-AchievementBackground", -- 84
				"Interface/ACHIEVEMENTFRAME/UI-GuildAchievement-Parchment-Horizontal-Desaturated", -- 85
				"Interface/ACHIEVEMENTFRAME/UI-GuildAchievement-Parchment-Horizontal", --86
				"Interface/DressUpFrame/DressUpBackground-BloodElf1",		-- 87
				"Interface/DressUpFrame/DressUpBackground-DeathKnight1",	-- 88
				"Interface/DressUpFrame/DressUpBackground-Draenei1",		-- 89
				"Interface/DressUpFrame/DressUpBackground-Dwarf1",		-- 90
				"Interface/DressUpFrame/DressUpBackground-Gnome1",		-- 91
				"Interface/DressUpFrame/DressUpBackground-Human1",		-- 92
				"Interface/DressUpFrame/DressUpBackground-NightElf1",		-- 93
				"Interface/DressUpFrame/DressUpBackground-Orc1",			-- 94
				"Interface/DressUpFrame/DressUpBackground-Tauren1",		-- 95
				"Interface/DressUpFrame/DressUpBackground-Troll1",			-- 96
				"Interface/DressUpFrame/DressUpBackground-Scourge1",		-- 97
				"Interface/FlavorImages/BloodElfLogo-small",				-- 98
				"Interface/FlavorImages/ScarletCrusadeLogo",				-- 100
				"Interface/FrameGeneral/UI-Background-Rock",				-- 101
				"Interface/FrameGeneral/UI-Background-Marble",			-- 102
				"Interface/HELPFRAME/DarkSandstone-Tile",				-- 103
				"Interface/HELPFRAME/Tileable-Parchment"}				-- 104